version: "3"

services:
  postgres:
    image: "postgres:13.5-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

volumes:
  postgres_data:
